// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class LivenessStartResult {
  LivenessStartResult({
    this.sessionId,
    this.previewTextureId,
    this.errorCode,
  });

  String? sessionId;

  int? previewTextureId;

  String? errorCode;

  Object encode() {
    return <Object?>[
      sessionId,
      previewTextureId,
      errorCode,
    ];
  }

  static LivenessStartResult decode(Object result) {
    result as List<Object?>;
    return LivenessStartResult(
      sessionId: result[0] as String?,
      previewTextureId: result[1] as int?,
      errorCode: result[2] as String?,
    );
  }
}

class LivenessStateEvent {
  LivenessStateEvent({
    this.sessionId,
    this.state,
    this.challenge,
    this.hint,
    this.uiMessageKey,
    this.attemptsUsed,
    this.attemptsMax,
    this.challengeIndex,
    this.challengeTotal,
    this.progress,
    this.failCategory,
  });

  String? sessionId;

  String? state;

  String? challenge;

  String? hint;

  String? uiMessageKey;

  int? attemptsUsed;

  int? attemptsMax;

  int? challengeIndex;

  int? challengeTotal;

  double? progress;

  String? failCategory;

  Object encode() {
    return <Object?>[
      sessionId,
      state,
      challenge,
      hint,
      uiMessageKey,
      attemptsUsed,
      attemptsMax,
      challengeIndex,
      challengeTotal,
      progress,
      failCategory,
    ];
  }

  static LivenessStateEvent decode(Object result) {
    result as List<Object?>;
    return LivenessStateEvent(
      sessionId: result[0] as String?,
      state: result[1] as String?,
      challenge: result[2] as String?,
      hint: result[3] as String?,
      uiMessageKey: result[4] as String?,
      attemptsUsed: result[5] as int?,
      attemptsMax: result[6] as int?,
      challengeIndex: result[7] as int?,
      challengeTotal: result[8] as int?,
      progress: result[9] as double?,
      failCategory: result[10] as String?,
    );
  }
}

class LivenessFinalResult {
  LivenessFinalResult({
    this.sessionId,
    this.outcome,
    this.nextAction,
    this.lockoutSeconds,
    this.validForSeconds,
  });

  String? sessionId;

  String? outcome;

  String? nextAction;

  int? lockoutSeconds;

  int? validForSeconds;

  Object encode() {
    return <Object?>[
      sessionId,
      outcome,
      nextAction,
      lockoutSeconds,
      validForSeconds,
    ];
  }

  static LivenessFinalResult decode(Object result) {
    result as List<Object?>;
    return LivenessFinalResult(
      sessionId: result[0] as String?,
      outcome: result[1] as String?,
      nextAction: result[2] as String?,
      lockoutSeconds: result[3] as int?,
      validForSeconds: result[4] as int?,
    );
  }
}

class _LivenessHostApiCodec extends StandardMessageCodec {
  const _LivenessHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LivenessStartResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return LivenessStartResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Pigeon bridge for the Android liveness gate (orchestration spec §7).
///
/// Regenerate the host/flutter code with:
///   ./tool/generate_pigeon.sh
///
/// Rules encoded here (spec R1–R5):
///   * Frames NEVER cross this channel (R2) — preview is a Flutter Texture,
///     analysis stays native. Only IDs, states and i18n keys travel.
///   * UI receives generic messages: no raw scores, no PAD detail (R5).
///   * The user never selects a challenge (R3) — the native orchestrator does.
class LivenessHostApi {
  /// Constructor for [LivenessHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LivenessHostApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _LivenessHostApiCodec();

  /// Start a gate for a role (RESIDENT | OPERATOR | SUPERVISOR).
  /// Returns the session id and the preview Texture id (R2).
  Future<LivenessStartResult> startSession(
      String arg_role, String? arg_userId) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LivenessHostApi.startSession', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_role, arg_userId]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as LivenessStartResult?)!;
    }
  }

  /// User cancel / lifecycle teardown (any state -> ABORTED, not an attempt).
  Future<void> cancelSession() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LivenessHostApi.cancelSession', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// True while the most recent PASSED gate is inside its validity window.
  /// Call before triggering the downstream capture/auth step (spec §8).
  Future<bool> isGateValid() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LivenessHostApi.isGateValid', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  /// Diagnostic snapshot (diagnostic mode only; no pixels).
  Future<Map<String?, String?>> diagnosticsSnapshot() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LivenessHostApi.diagnosticsSnapshot', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as Map<Object?, Object?>?)!.cast<String?, String?>();
    }
  }
}

class _LivenessFlutterApiCodec extends StandardMessageCodec {
  const _LivenessFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LivenessFinalResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is LivenessStateEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return LivenessFinalResult.decode(readValue(buffer)!);
      case 129:
        return LivenessStateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class LivenessFlutterApi {
  static const MessageCodec<Object?> codec = _LivenessFlutterApiCodec();

  /// Per-state UI event; see [LivenessStateEvent.state] + [uiMessageKey].
  void onState(LivenessStateEvent event);

  /// Terminal outcome (PASSED | TERMINAL_FAILURE | ABORTED).
  void onFinal(LivenessFinalResult result);

  static void setup(LivenessFlutterApi? api,
      {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.LivenessFlutterApi.onState', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.LivenessFlutterApi.onState was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LivenessStateEvent? arg_event =
              (args[0] as LivenessStateEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.LivenessFlutterApi.onState was null, expected non-null LivenessStateEvent.');
          api.onState(arg_event!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.LivenessFlutterApi.onFinal', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.LivenessFlutterApi.onFinal was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LivenessFinalResult? arg_result =
              (args[0] as LivenessFinalResult?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.LivenessFlutterApi.onFinal was null, expected non-null LivenessFinalResult.');
          api.onFinal(arg_result!);
          return;
        });
      }
    }
  }
}
