package io.mosip.liveness.audit;

import io.mosip.liveness.models.entity.AuditLog;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Chained hashing for the config audit trail.
 *
 * <p>Each entry stores {@code prev_hash} (the previous entry's
 * {@code entry_hash}) and {@code entry_hash = H(prev_hash ‖ entry)}. Editing a
 * stored row changes its content so its own hash no longer matches; deleting one
 * leaves every later entry pointing at a hash that no longer follows from its
 * predecessor. Both are detectable, which is what makes the trail worth more
 * than an append-only hope.</p>
 *
 * <h2>Why the canonical form is not just the row</h2>
 *
 * <p>{@code details} round-trips through
 * {@link io.mosip.liveness.models.converter.StringObjectMapJsonConverter}, whose
 * {@code convertToEntityAttribute} returns a plain {@code HashMap}. Hash order
 * is therefore <em>not</em> stable across a database round-trip: hashing what
 * came out of the map on write and hashing what came back on verify would
 * disagree for reasons that have nothing to do with tampering, and every
 * verification would fail. So the payload is canonicalised first — map keys
 * sorted recursively, collections ordered, every component length-prefixed — and
 * only that stable form is hashed.</p>
 *
 * <p>Length prefixing is not decoration. Without it a value containing the
 * separator could be re-split into different fields, letting two genuinely
 * different entries hash the same: {@code "a|b", "c"} and {@code "a", "b|c"}
 * would concatenate identically.</p>
 *
 * <h2>When the hash is computed</h2>
 *
 * <p>Before the INSERT, never after. {@code id} is generated by the database
 * at persist time and {@code createdAt} by {@code @PrePersist}, so both must be
 * known up front — {@code createdAt} is set explicitly by the caller for
 * exactly this reason. Recomputing after the insert is not an option: the
 * immutability triggers added in {@code V9} reject the UPDATE.</p>
 *
 * <h2>What this does and does not buy</h2>
 *
 * <p>This detects corruption, accidental edits and deletion by anyone
 * who does not recompute the chain — including the admin-key holder editing
 * through the application, which is the realistic threat here. An attacker with
 * write access to the database could read the stored hashes and rebuild the
 * chain, so the hash is <em>keyed</em> by {@link AuditChainKey} with a secret
 * the database does not hold: without it, a rebuilt chain fails verification
 * outright instead of verifying perfectly on its own.</p>
 *
 * <p>With no secret configured the hash falls back to plain
 * {@code SHA-256} of the same canonical string — tamper-detecting, but not
 * tamper-proofing against a database writer, and reported as such by
 * {@code GET /api/v1/config/audit/verify} ({@code hmac: false}). The
 * canonical form is unchanged, which is what makes the two modes comparable:
 * a chain written before the secret was configured still verifies once it is
 * set, as long as every entry was written in the same mode as the one being
 * verified. Writing keyed and verifying unkeyed (a missing or rotated secret)
 * is reported as a break at the first entry, never accepted as a downgrade.</p>
 */
public final class AuditChain {

    /** {@code prev_hash} of the first entry in a chain. */
    public static final String GENESIS = "0".repeat(64);

    private static final char FIELD_SEP = '\0';

    private AuditChain() {
    }

    /**
     * The canonical string an entry's hash is computed over. Exposed so the
     * format can be asserted directly in tests — if this ever changes, every
     * previously written hash becomes unverifiable and needs a migration note.
     */
    public static String canonical(AuditLog entry) {
        StringBuilder sb = new StringBuilder();
        field(sb, entry.getPrevHash() == null ? "" : entry.getPrevHash());
        // The id is deliberately NOT hashed. It is assigned by Hibernate's
        // @GeneratedValue at INSERT, so at hash time it is still null and the
        // canonical form would change the moment the row lands — and it cannot
        // be hashed afterwards, because the immutability trigger rejects the
        // UPDATE that would write the corrected hash. Position in the chain,
        // plus prev_hash, already binds an entry uniquely.
        field(sb, entry.getEventType());
        field(sb, entry.getWorkflowType() == null ? null : entry.getWorkflowType().name());
        field(sb, entry.getSession() == null || entry.getSession().getId() == null
                ? null : entry.getSession().getId().toString());
        // Millisecond precision on both sides: PostgreSQL TIMESTAMPTZ stores
        // microseconds while OffsetDateTime.now() carries nanoseconds, so
        // hashing the raw value would fail to reproduce after a round-trip.
        field(sb, entry.getCreatedAt() == null ? null
                : Long.toString(entry.getCreatedAt().toInstant().toEpochMilli()));
        payload(sb, entry.getDetails());
        return sb.toString();
    }

    /**
     * The entry's {@code entry_hash}, keyed by the supplied secret: HMAC when
     * {@link AuditChainKey#isKeyed()}, plain SHA-256 in fallback mode. Writing
     * and verification must use the same key — see {@link AuditChainKey}.
     */
    public static String hashOf(AuditLog entry, AuditChainKey key) {
        return key.hash(canonical(entry));
    }

    private static void field(StringBuilder sb, String value) {
        sb.append('s').append(value == null ? -1 : value.length()).append(':');
        if (value != null) {
            sb.append(value);
        }
        sb.append(FIELD_SEP);
    }

    /** Recursive, order-independent encoding of the details JSON. */
    private static void payload(StringBuilder sb, Object value) {
        if (value == null) {
            sb.append("null");
        } else if (value instanceof Map<?, ?> map) {
            sb.append('{');
            map.entrySet().stream()
                    .map(e -> Map.entry(String.valueOf(e.getKey()), e.getValue()))
                    .sorted(Comparator.comparing(Map.Entry::getKey))
                    .forEach(e -> {
                        field(sb, e.getKey());
                        payload(sb, e.getValue());
                    });
            sb.append('}');
        } else if (value instanceof Collection<?> list) {
            sb.append('[');
            for (Object item : list) {
                payload(sb, item);
                sb.append(',');
            }
            sb.append(']');
        } else if (value instanceof Boolean b) {
            sb.append(b.booleanValue() ? "true" : "false");
        } else if (value instanceof Number n) {
            // Jackson preserves the textual form of the number across a
            // round-trip (0.8 -> "0.8" -> 0.8), so toString is stable here.
            field(sb, n.toString());
        } else {
            field(sb, String.valueOf(value));
        }
    }

    /**
     * Walks a chain in order and reports the first entry that does not follow
     * from its predecessor.
     *
     * <p>A missing {@code entry_hash} means "unverifiable" rather than "broken"
     * — entries written before the chain existed carry no hash and are skipped,
     * so the walk starts at the first hashed entry.</p>
     *
     * @param ordered entries oldest first; must be the full chain, not a page
     * @param key the secret the entries were written with, plus the previous
     *        one while historical hashes still need it
     * @return the first break, or empty when every link checks out
     */
    public static Optional<Break> verify(List<AuditLog> ordered, AuditChainKey key) {
        return verifyChain(ordered, key).breakInfo();
    }

    /**
     * Walks the chain and also reports whether any entry verified only under
     * the previous secret.
     *
     * <p>That second fact tells an operator whether any historical row still
     * needs the previous secret. The chain can be intact while still needing
     * that key; the immutable rows cannot be re-keyed in place.</p>
     */
    public static Verification verifyChain(List<AuditLog> ordered, AuditChainKey key) {
        String expectedPrev = GENESIS;
        int index = 0;
        boolean retiredUsed = false;
        Break firstBreak = null;
        for (AuditLog entry : ordered) {
            if (entry.getEntryHash() == null) {
                continue;               // legacy row, predates the chain
            }
            // The previous secret preserves verification of historical rows;
            // see AuditChainKey for the retention limit.
            AuditChainKey.Match match = key.match(canonical(entry), entry.getEntryHash());
            if (match == AuditChainKey.Match.RETIRED) {
                retiredUsed = true;
            }
            boolean selfConsistent = match != AuditChainKey.Match.NONE;
            boolean linked = expectedPrev.equals(entry.getPrevHash());
            if (firstBreak == null && (!selfConsistent || !linked)) {
                firstBreak = new Break(index, entry.getId(),
                        selfConsistent ? null : hashOf(entry, key), entry.getEntryHash(),
                        entry.getPrevHash(), expectedPrev);
            }
            expectedPrev = entry.getEntryHash();
            index++;
        }
        return new Verification(Optional.ofNullable(firstBreak), retiredUsed);
    }

    /**
     * The outcome of a walk: where it stopped, if anywhere, and whether the
     * previous secret was needed to get there.
     *
     * @param breakInfo the first break, or empty when every link checks out
     * @param retiredKeyHashes {@code true} when at least one entry reproduced
     *        only under the previous secret
     */
    public record Verification(Optional<Break> breakInfo, boolean retiredKeyHashes) {

        public boolean intact() {
            return breakInfo.isEmpty();
        }
    }

    /**
     * Where and how the chain stopped verifying.
     *
     * <p>{@code selfConsistent} false means the row's own content was altered.
     * Otherwise the row is intact but no longer follows its predecessor, which
     * is what a deleted entry looks like.</p>
     */
    public record Break(int index, java.util.UUID id, String recomputedHash, String storedHash,
                        String storedPrevHash, String expectedPrevHash) {

        public boolean contentChanged() {
            return recomputedHash != null;
        }
    }
}
