// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package io.mosip.registration.liveness.pigeon;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Liveness {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LivenessStartResult {
    private @Nullable String sessionId;

    public @Nullable String getSessionId() {
      return sessionId;
    }

    public void setSessionId(@Nullable String setterArg) {
      this.sessionId = setterArg;
    }

    private @Nullable Long previewTextureId;

    public @Nullable Long getPreviewTextureId() {
      return previewTextureId;
    }

    public void setPreviewTextureId(@Nullable Long setterArg) {
      this.previewTextureId = setterArg;
    }

    private @Nullable String errorCode;

    public @Nullable String getErrorCode() {
      return errorCode;
    }

    public void setErrorCode(@Nullable String setterArg) {
      this.errorCode = setterArg;
    }

    public static final class Builder {

      private @Nullable String sessionId;

      public @NonNull Builder setSessionId(@Nullable String setterArg) {
        this.sessionId = setterArg;
        return this;
      }

      private @Nullable Long previewTextureId;

      public @NonNull Builder setPreviewTextureId(@Nullable Long setterArg) {
        this.previewTextureId = setterArg;
        return this;
      }

      private @Nullable String errorCode;

      public @NonNull Builder setErrorCode(@Nullable String setterArg) {
        this.errorCode = setterArg;
        return this;
      }

      public @NonNull LivenessStartResult build() {
        LivenessStartResult pigeonReturn = new LivenessStartResult();
        pigeonReturn.setSessionId(sessionId);
        pigeonReturn.setPreviewTextureId(previewTextureId);
        pigeonReturn.setErrorCode(errorCode);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(sessionId);
      toListResult.add(previewTextureId);
      toListResult.add(errorCode);
      return toListResult;
    }

    static @NonNull LivenessStartResult fromList(@NonNull ArrayList<Object> list) {
      LivenessStartResult pigeonResult = new LivenessStartResult();
      Object sessionId = list.get(0);
      pigeonResult.setSessionId((String) sessionId);
      Object previewTextureId = list.get(1);
      pigeonResult.setPreviewTextureId((previewTextureId == null) ? null : ((previewTextureId instanceof Integer) ? (Integer) previewTextureId : (Long) previewTextureId));
      Object errorCode = list.get(2);
      pigeonResult.setErrorCode((String) errorCode);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LivenessStateEvent {
    private @Nullable String sessionId;

    public @Nullable String getSessionId() {
      return sessionId;
    }

    public void setSessionId(@Nullable String setterArg) {
      this.sessionId = setterArg;
    }

    private @Nullable String state;

    public @Nullable String getState() {
      return state;
    }

    public void setState(@Nullable String setterArg) {
      this.state = setterArg;
    }

    private @Nullable String challenge;

    public @Nullable String getChallenge() {
      return challenge;
    }

    public void setChallenge(@Nullable String setterArg) {
      this.challenge = setterArg;
    }

    private @Nullable String hint;

    public @Nullable String getHint() {
      return hint;
    }

    public void setHint(@Nullable String setterArg) {
      this.hint = setterArg;
    }

    private @Nullable String uiMessageKey;

    public @Nullable String getUiMessageKey() {
      return uiMessageKey;
    }

    public void setUiMessageKey(@Nullable String setterArg) {
      this.uiMessageKey = setterArg;
    }

    private @Nullable Long attemptsUsed;

    public @Nullable Long getAttemptsUsed() {
      return attemptsUsed;
    }

    public void setAttemptsUsed(@Nullable Long setterArg) {
      this.attemptsUsed = setterArg;
    }

    private @Nullable Long attemptsMax;

    public @Nullable Long getAttemptsMax() {
      return attemptsMax;
    }

    public void setAttemptsMax(@Nullable Long setterArg) {
      this.attemptsMax = setterArg;
    }

    private @Nullable Long challengeIndex;

    public @Nullable Long getChallengeIndex() {
      return challengeIndex;
    }

    public void setChallengeIndex(@Nullable Long setterArg) {
      this.challengeIndex = setterArg;
    }

    private @Nullable Long challengeTotal;

    public @Nullable Long getChallengeTotal() {
      return challengeTotal;
    }

    public void setChallengeTotal(@Nullable Long setterArg) {
      this.challengeTotal = setterArg;
    }

    private @Nullable Double progress;

    public @Nullable Double getProgress() {
      return progress;
    }

    public void setProgress(@Nullable Double setterArg) {
      this.progress = setterArg;
    }

    private @Nullable String failCategory;

    public @Nullable String getFailCategory() {
      return failCategory;
    }

    public void setFailCategory(@Nullable String setterArg) {
      this.failCategory = setterArg;
    }

    public static final class Builder {

      private @Nullable String sessionId;

      public @NonNull Builder setSessionId(@Nullable String setterArg) {
        this.sessionId = setterArg;
        return this;
      }

      private @Nullable String state;

      public @NonNull Builder setState(@Nullable String setterArg) {
        this.state = setterArg;
        return this;
      }

      private @Nullable String challenge;

      public @NonNull Builder setChallenge(@Nullable String setterArg) {
        this.challenge = setterArg;
        return this;
      }

      private @Nullable String hint;

      public @NonNull Builder setHint(@Nullable String setterArg) {
        this.hint = setterArg;
        return this;
      }

      private @Nullable String uiMessageKey;

      public @NonNull Builder setUiMessageKey(@Nullable String setterArg) {
        this.uiMessageKey = setterArg;
        return this;
      }

      private @Nullable Long attemptsUsed;

      public @NonNull Builder setAttemptsUsed(@Nullable Long setterArg) {
        this.attemptsUsed = setterArg;
        return this;
      }

      private @Nullable Long attemptsMax;

      public @NonNull Builder setAttemptsMax(@Nullable Long setterArg) {
        this.attemptsMax = setterArg;
        return this;
      }

      private @Nullable Long challengeIndex;

      public @NonNull Builder setChallengeIndex(@Nullable Long setterArg) {
        this.challengeIndex = setterArg;
        return this;
      }

      private @Nullable Long challengeTotal;

      public @NonNull Builder setChallengeTotal(@Nullable Long setterArg) {
        this.challengeTotal = setterArg;
        return this;
      }

      private @Nullable Double progress;

      public @NonNull Builder setProgress(@Nullable Double setterArg) {
        this.progress = setterArg;
        return this;
      }

      private @Nullable String failCategory;

      public @NonNull Builder setFailCategory(@Nullable String setterArg) {
        this.failCategory = setterArg;
        return this;
      }

      public @NonNull LivenessStateEvent build() {
        LivenessStateEvent pigeonReturn = new LivenessStateEvent();
        pigeonReturn.setSessionId(sessionId);
        pigeonReturn.setState(state);
        pigeonReturn.setChallenge(challenge);
        pigeonReturn.setHint(hint);
        pigeonReturn.setUiMessageKey(uiMessageKey);
        pigeonReturn.setAttemptsUsed(attemptsUsed);
        pigeonReturn.setAttemptsMax(attemptsMax);
        pigeonReturn.setChallengeIndex(challengeIndex);
        pigeonReturn.setChallengeTotal(challengeTotal);
        pigeonReturn.setProgress(progress);
        pigeonReturn.setFailCategory(failCategory);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(11);
      toListResult.add(sessionId);
      toListResult.add(state);
      toListResult.add(challenge);
      toListResult.add(hint);
      toListResult.add(uiMessageKey);
      toListResult.add(attemptsUsed);
      toListResult.add(attemptsMax);
      toListResult.add(challengeIndex);
      toListResult.add(challengeTotal);
      toListResult.add(progress);
      toListResult.add(failCategory);
      return toListResult;
    }

    static @NonNull LivenessStateEvent fromList(@NonNull ArrayList<Object> list) {
      LivenessStateEvent pigeonResult = new LivenessStateEvent();
      Object sessionId = list.get(0);
      pigeonResult.setSessionId((String) sessionId);
      Object state = list.get(1);
      pigeonResult.setState((String) state);
      Object challenge = list.get(2);
      pigeonResult.setChallenge((String) challenge);
      Object hint = list.get(3);
      pigeonResult.setHint((String) hint);
      Object uiMessageKey = list.get(4);
      pigeonResult.setUiMessageKey((String) uiMessageKey);
      Object attemptsUsed = list.get(5);
      pigeonResult.setAttemptsUsed((attemptsUsed == null) ? null : ((attemptsUsed instanceof Integer) ? (Integer) attemptsUsed : (Long) attemptsUsed));
      Object attemptsMax = list.get(6);
      pigeonResult.setAttemptsMax((attemptsMax == null) ? null : ((attemptsMax instanceof Integer) ? (Integer) attemptsMax : (Long) attemptsMax));
      Object challengeIndex = list.get(7);
      pigeonResult.setChallengeIndex((challengeIndex == null) ? null : ((challengeIndex instanceof Integer) ? (Integer) challengeIndex : (Long) challengeIndex));
      Object challengeTotal = list.get(8);
      pigeonResult.setChallengeTotal((challengeTotal == null) ? null : ((challengeTotal instanceof Integer) ? (Integer) challengeTotal : (Long) challengeTotal));
      Object progress = list.get(9);
      pigeonResult.setProgress((Double) progress);
      Object failCategory = list.get(10);
      pigeonResult.setFailCategory((String) failCategory);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LivenessFinalResult {
    private @Nullable String sessionId;

    public @Nullable String getSessionId() {
      return sessionId;
    }

    public void setSessionId(@Nullable String setterArg) {
      this.sessionId = setterArg;
    }

    private @Nullable String outcome;

    public @Nullable String getOutcome() {
      return outcome;
    }

    public void setOutcome(@Nullable String setterArg) {
      this.outcome = setterArg;
    }

    private @Nullable String nextAction;

    public @Nullable String getNextAction() {
      return nextAction;
    }

    public void setNextAction(@Nullable String setterArg) {
      this.nextAction = setterArg;
    }

    private @Nullable Long lockoutSeconds;

    public @Nullable Long getLockoutSeconds() {
      return lockoutSeconds;
    }

    public void setLockoutSeconds(@Nullable Long setterArg) {
      this.lockoutSeconds = setterArg;
    }

    private @Nullable Long validForSeconds;

    public @Nullable Long getValidForSeconds() {
      return validForSeconds;
    }

    public void setValidForSeconds(@Nullable Long setterArg) {
      this.validForSeconds = setterArg;
    }

    public static final class Builder {

      private @Nullable String sessionId;

      public @NonNull Builder setSessionId(@Nullable String setterArg) {
        this.sessionId = setterArg;
        return this;
      }

      private @Nullable String outcome;

      public @NonNull Builder setOutcome(@Nullable String setterArg) {
        this.outcome = setterArg;
        return this;
      }

      private @Nullable String nextAction;

      public @NonNull Builder setNextAction(@Nullable String setterArg) {
        this.nextAction = setterArg;
        return this;
      }

      private @Nullable Long lockoutSeconds;

      public @NonNull Builder setLockoutSeconds(@Nullable Long setterArg) {
        this.lockoutSeconds = setterArg;
        return this;
      }

      private @Nullable Long validForSeconds;

      public @NonNull Builder setValidForSeconds(@Nullable Long setterArg) {
        this.validForSeconds = setterArg;
        return this;
      }

      public @NonNull LivenessFinalResult build() {
        LivenessFinalResult pigeonReturn = new LivenessFinalResult();
        pigeonReturn.setSessionId(sessionId);
        pigeonReturn.setOutcome(outcome);
        pigeonReturn.setNextAction(nextAction);
        pigeonReturn.setLockoutSeconds(lockoutSeconds);
        pigeonReturn.setValidForSeconds(validForSeconds);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(5);
      toListResult.add(sessionId);
      toListResult.add(outcome);
      toListResult.add(nextAction);
      toListResult.add(lockoutSeconds);
      toListResult.add(validForSeconds);
      return toListResult;
    }

    static @NonNull LivenessFinalResult fromList(@NonNull ArrayList<Object> list) {
      LivenessFinalResult pigeonResult = new LivenessFinalResult();
      Object sessionId = list.get(0);
      pigeonResult.setSessionId((String) sessionId);
      Object outcome = list.get(1);
      pigeonResult.setOutcome((String) outcome);
      Object nextAction = list.get(2);
      pigeonResult.setNextAction((String) nextAction);
      Object lockoutSeconds = list.get(3);
      pigeonResult.setLockoutSeconds((lockoutSeconds == null) ? null : ((lockoutSeconds instanceof Integer) ? (Integer) lockoutSeconds : (Long) lockoutSeconds));
      Object validForSeconds = list.get(4);
      pigeonResult.setValidForSeconds((validForSeconds == null) ? null : ((validForSeconds instanceof Integer) ? (Integer) validForSeconds : (Long) validForSeconds));
      return pigeonResult;
    }
  }

  public interface Result<T> {
    @SuppressWarnings("UnknownNullness")
    void success(T result);

    void error(@NonNull Throwable error);
  }

  private static class LivenessHostApiCodec extends StandardMessageCodec {
    public static final LivenessHostApiCodec INSTANCE = new LivenessHostApiCodec();

    private LivenessHostApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return LivenessStartResult.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof LivenessStartResult) {
        stream.write(128);
        writeValue(stream, ((LivenessStartResult) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /**
   * Pigeon bridge for the Android liveness gate (orchestration spec §7).
   *
   * Regenerate the host/flutter code with:
   *   ./tool/generate_pigeon.sh
   *
   * Rules encoded here (spec R1–R5):
   *   * Frames NEVER cross this channel (R2) — preview is a Flutter Texture,
   *     analysis stays native. Only IDs, states and i18n keys travel.
   *   * UI receives generic messages: no raw scores, no PAD detail (R5).
   *   * The user never selects a challenge (R3) — the native orchestrator does.
   *
   * Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface LivenessHostApi {
    /**
     * Start a gate for a role (RESIDENT | OPERATOR | SUPERVISOR).
     * Returns the session id and the preview Texture id (R2).
     */
    void startSession(@NonNull String role, @Nullable String userId, @NonNull Result<LivenessStartResult> result);
    /** User cancel / lifecycle teardown (any state -> ABORTED, not an attempt). */
    void cancelSession();
    /**
     * True while the most recent PASSED gate is inside its validity window.
     * Call before triggering the downstream capture/auth step (spec §8).
     */
    @NonNull 
    Boolean isGateValid();
    /** Diagnostic snapshot (diagnostic mode only; no pixels). */
    @NonNull 
    Map<String, String> diagnosticsSnapshot();

    /** The codec used by LivenessHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return LivenessHostApiCodec.INSTANCE;
    }
    /**Sets up an instance of `LivenessHostApi` to handle messages through the `binaryMessenger`. */
    static void setup(@NonNull BinaryMessenger binaryMessenger, @Nullable LivenessHostApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.LivenessHostApi.startSession", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String roleArg = (String) args.get(0);
                String userIdArg = (String) args.get(1);
                Result<LivenessStartResult> resultCallback =
                    new Result<LivenessStartResult>() {
                      public void success(LivenessStartResult result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.startSession(roleArg, userIdArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.LivenessHostApi.cancelSession", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                try {
                  api.cancelSession();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.LivenessHostApi.isGateValid", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                try {
                  Boolean output = api.isGateValid();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.LivenessHostApi.diagnosticsSnapshot", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                try {
                  Map<String, String> output = api.diagnosticsSnapshot();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  private static class LivenessFlutterApiCodec extends StandardMessageCodec {
    public static final LivenessFlutterApiCodec INSTANCE = new LivenessFlutterApiCodec();

    private LivenessFlutterApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return LivenessFinalResult.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 129:
          return LivenessStateEvent.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof LivenessFinalResult) {
        stream.write(128);
        writeValue(stream, ((LivenessFinalResult) value).toList());
      } else if (value instanceof LivenessStateEvent) {
        stream.write(129);
        writeValue(stream, ((LivenessStateEvent) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class LivenessFlutterApi {
    private final @NonNull BinaryMessenger binaryMessenger;

    public LivenessFlutterApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this.binaryMessenger = argBinaryMessenger;
    }

    /** Public interface for sending reply. */ 
    @SuppressWarnings("UnknownNullness")
    public interface Reply<T> {
      void reply(T reply);
    }
    /** The codec used by LivenessFlutterApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return LivenessFlutterApiCodec.INSTANCE;
    }
    /** Per-state UI event; see [LivenessStateEvent.state] + [uiMessageKey]. */
    public void onState(@NonNull LivenessStateEvent eventArg, @NonNull Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, "dev.flutter.pigeon.LivenessFlutterApi.onState", getCodec());
      channel.send(
          new ArrayList<Object>(Collections.singletonList(eventArg)),
          channelReply -> callback.reply(null));
    }
    /** Terminal outcome (PASSED | TERMINAL_FAILURE | ABORTED). */
    public void onFinal(@NonNull LivenessFinalResult resultArg, @NonNull Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, "dev.flutter.pigeon.LivenessFlutterApi.onFinal", getCodec());
      channel.send(
          new ArrayList<Object>(Collections.singletonList(resultArg)),
          channelReply -> callback.reply(null));
    }
  }
}
